export default {
  id: 'week2_1',
  cycleID: 1,
  status: 'active',
  week: 2,
  rehab: false,
  movements: ['SQ_A', 'BN_C', 'DL_B', 'BN_T'],
  accLifts: [
    {
      volume: {
        LR: [6, 8],
        TUT: [30, 60],
        HR: [10, 12],
        MR: [8, 10],
      },
      sets: 3,
      status: 'pending',
      exercise: {
        exerciseShortcode: '',
        category: 'QD',
        canChange: true,
        exerciseName: '',
      },
      liftID: 0,
      intensity: [3, 4],
      movement: 'QD',
    },
    {
      volume: {
        LR: [6, 8],
        TUT: [30, 60],
        HR: [10, 12],
        MR: [8, 10],
      },
      sets: 3,
      status: 'pending',
      exercise: {
        exerciseShortcode: '',
        category: 'AB',
        canChange: true,
        exerciseName: '',
      },
      liftID: 2,
      intensity: [3, 4],
      movement: 'AB',
    },
  ],
  day: 1,
  exercises: ['SQ0', 'BN62', 'DL118', 'BN0'],
  blockType: 'S51_4',
  sessionStart: {
    seconds: 1662690283,
    nanoseconds: 462000000,
  },
  readiness: [2, 2, 2, 2],
  mainLifts: [
    {
      dropRepAdj: [0, 0, 0],
      exercise: {
        type: 'A',
        exerciseShortcode: 'SQ0',
        category: 'SQ_5_A_S4',
        weakness: 5,
        movement: 'SQ',
      },
      sets: 7,
      liftID: 0,
      volume: {
        MR: {
          rpe: [6, 7],
          percentage: [0.76, 0.8],
          reps: [3],
        },
        LR: {
          rpe: [6, 7],
          percentage: [0.76, 0.8],
          reps: [3],
        },
        HR: {
          rpe: [6, 7],
          percentage: [0.76, 0.8],
          reps: [3],
        },
      },
      dropset: true,
      dropPercentage: [0.92, 0.92, 0.92],
      shifter: 'FALSE',
      movement: 'squat',
    },
    {
      dropRepAdj: [null],
      exercise: {
        type: 'C',
        exerciseShortcode: 'BN62',
        category: 'BN_1_C_S4',
        weakness: 1,
        movement: 'BN',
      },
      sets: 5,
      liftID: 1,
      volume: {
        MR: {
          rpe: [6],
          percentage: [0.68, 0.72],
          reps: [3],
        },
        LR: {
          rpe: [6],
          percentage: [0.68, 0.72],
          reps: [3],
        },
        HR: {
          rpe: [6],
          percentage: [0.68, 0.72],
          reps: [3],
        },
      },
      dropset: false,
      dropPercentage: [null],
      shifter: 'FALSE',
      movement: 'bench',
    },
    {
      dropRepAdj: [null],
      exercise: {
        type: 'B',
        exerciseShortcode: 'DL118',
        category: 'DL_4_B_S4',
        weakness: 4,
        movement: 'DL',
      },
      sets: 6,
      liftID: 2,
      volume: {
        MR: {
          rpe: [6],
          percentage: [0.72, 0.76],
          reps: [2],
        },
        LR: {
          rpe: [6],
          percentage: [0.72, 0.76],
          reps: [2],
        },
        HR: {
          rpe: [6],
          percentage: [0.72, 0.76],
          reps: [2],
        },
      },
      dropset: false,
      dropPercentage: [null],
      shifter: 'FALSE',
      movement: 'deadlift',
    },
    {
      dropRepAdj: [null],
      exercise: {
        type: 'T',
        exerciseShortcode: 'BN0',
        category: 'BN_1_T_S4',
        weakness: 1,
        movement: 'BN',
      },
      sets: 3,
      liftID: 3,
      volume: {
        MR: {
          rpe: [6],
          percentage: [0.5, 0.7],
          reps: [2, 4],
        },
        LR: {
          rpe: [6],
          percentage: [0.5, 0.7],
          reps: [2, 4],
        },
        HR: {
          rpe: [6],
          percentage: [0.5, 0.7],
          reps: [2, 4],
        },
      },
      dropset: false,
      dropPercentage: [null],
      shifter: 'FALSE',
      movement: 'bench',
    },
  ],
}
