export const topSetValues = [
  {
    set: 1,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'topSet',
    reps: [3],
    percentage: [0.74, 0.78],
    rpe: [6, 7],
    hasDrop: true,
    intensity: [0.74, 0.78],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 2,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'dropSet',
    reps: [3],
    percentage: [0.92],
    rpe: [6],
    hasDrop: true,
    intensity: [0.92],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 3,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'dropSet',
    reps: [3],
    percentage: [0.92],
    rpe: [6],
    hasDrop: true,
    intensity: [0.92],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 4,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'dropSet',
    reps: [3],
    percentage: [0.92],
    rpe: [6],
    hasDrop: true,
    intensity: [0.92],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 5,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'dropSet',
    reps: [3],
    percentage: [0.92],
    rpe: [6],
    hasDrop: true,
    intensity: [0.92],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 6,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'dropSet',
    reps: [3],
    percentage: [0.92],
    rpe: [6],
    hasDrop: true,
    intensity: [0.92],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 5,
    isPerSide: false,
    isBodyweight: false,
  },
]

export const straightSetsValues = [
  {
    set: 1,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'straightSets',
    reps: [3],
    percentage: [0.7, 0.74],
    rpe: [6],
    hasDrop: false,
    intensity: [0.7, 0.74],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 2.5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 2,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'straightSets',
    reps: [3],
    percentage: [0.7, 0.74],
    rpe: [6],
    hasDrop: false,
    intensity: [0.7, 0.74],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 2.5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 3,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'straightSets',
    reps: [3],
    percentage: [0.7, 0.74],
    rpe: [6],
    hasDrop: false,
    intensity: [0.7, 0.74],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 2.5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 4,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'straightSets',
    reps: [3],
    percentage: [0.7, 0.74],
    rpe: [6],
    hasDrop: false,
    intensity: [0.7, 0.74],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 2.5,
    isPerSide: false,
    isBodyweight: false,
  },
  {
    set: 5,
    setRange: null,
    status: 'pending',
    performance: {
      weight: '',
      units: '',
      reps: '',
      rpe: '',
    },
    type: 'straightSets',
    reps: [3],
    percentage: [0.7, 0.74],
    rpe: [6],
    hasDrop: false,
    intensity: [0.7, 0.74],
    intensityAdj: 0,
    shifter: 0,
    isDeload: false,
    weightIncrement: 2.5,
    isPerSide: false,
    isBodyweight: false,
  },
]
